import csv

lineas_csv = [
    ["edad","pais","trabaja"],
    ["18","Argentina","False"],
    ["19","Argentina","True"],
    ["20","Argentina","False"],
    ["21","Argentina","True"],
    ["22","Argentina","True"],
    ["23","Argentina","False"],
    ["24","Argentina","True"],
    ["25","Argentina","True"],
    ["26","Argentina","False"],
    ["27","Argentina","True"],
    ["18","Chile","False"],
    ["19","Chile","True"],
    ["20","Chile","True"],
    ["21","Chile","False"],
    ["22","Chile","True"],
    ["23","Chile","True"],
    ["24","Chile","False"],
    ["25","Chile","True"],
    ["26","Chile","True"],
    ["27","Chile","False"],
    ["18","Uruguay","True"],
    ["19","Uruguay","False"],
    ["20","Uruguay","True"],
    ["21","Uruguay","True"],
    ["22","Uruguay","False"],
    ["23","Uruguay","True"],
    ["24","Uruguay","False"],
    ["25","Uruguay","True"],
    ["26","Uruguay","True"],
    ["27","Uruguay","False"],
    ["18","Brasil","False"],
    ["19","Brasil","True"],
    ["20","Brasil","False"],
    ["21","Brasil","True"],
    ["22","Brasil","True"],
    ["23","Brasil","False"],
    ["24","Brasil","True"],
    ["25","Brasil","True"],
    ["26","Brasil","False"],
    ["27","Brasil","True"],
    ["18","Peru","True"],
    ["19","Peru","False"],
    ["20","Peru","True"],
    ["21","Peru","True"],
    ["22","Peru","False"],
    ["23","Peru","True"],
    ["24","Peru","False"],
    ["25","Peru","True"],
    ["26","Peru","True"],
    ["27","Peru","False"],
    ["18","Mexico","False"],
    ["19","Mexico","True"],
    ["20","Mexico","True"],
    ["21","Mexico","False"],
    ["22","Mexico","True"],
    ["23","Mexico","False"],
    ["24","Mexico","True"],
    ["25","Mexico","True"],
    ["26","Mexico","False"],
    ["27","Mexico","True"],
    ["18","España","True"],
    ["19","España","False"],
    ["20","España","True"],
    ["21","España","True"],
    ["22","España","False"],
    ["23","España","True"],
    ["24","España","False"],
    ["25","España","True"],
    ["26","España","True"],
    ["27","España","False"],
    ["18","Colombia","True"],
    ["19","Colombia","False"],
    ["20","Colombia","True"],
    ["21","Colombia","True"],
    ["22","Colombia","False"],
    ["23","Colombia","True"],
    ["24","Colombia","False"]
]

with open("datos_empleo.csv", mode="w", newline="", encoding="utf-8") as archivo:
    escritor = csv.writer(archivo)
    escritor.writerows(lineas_csv)

print("Archivo CSV generado correctamente.")
